# Generated by Django 2.1.1 on 2018-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0002_auto_20180902_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlet_category',
            name='color',
            field=models.CharField(default='#cccccc', max_length=11),
        ),
    ]
