# Generated by Django 2.1.1 on 2018-09-04 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0004_inlet_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlet',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 9, 4, 17, 44, 53, 227521, tzinfo=utc)),
        ),
    ]
