# Generated by Django 2.1.1 on 2018-09-04 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0005_auto_20180904_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlet',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 9, 4, 17, 53, 24, 557377), verbose_name='Date'),
        ),
    ]
