# Generated by Django 2.1.1 on 2018-09-04 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0006_auto_20180904_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlet',
            name='created_at',
        ),
        migrations.AddField(
            model_name='inlet',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 9, 4, 17, 55, 27, 266464), verbose_name='Date'),
        ),
    ]
