# Generated by Django 2.1.1 on 2018-09-04 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0007_auto_20180904_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlet',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
    ]
